import { Inter } from 'next/font/google';
import './globals.css';
import { home } from "@/metadata.json";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: home.title,
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params: { locale },
}) {
    return (
        <html lang={locale}>
            <body className={inter.className}>
                {children}
            </body>
        </html>
    );
}